# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-19 14:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10)),
                ('quantity', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SlackAuth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=200)),
                ('team_id', models.CharField(max_length=30, unique=True)),
                ('team_name', models.CharField(max_length=200)),
                ('bot_id', models.CharField(max_length=30)),
                ('bot_access_token', models.CharField(max_length=200)),
                ('general_channel_id', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TalkUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=300)),
                ('slack_id', models.CharField(blank=True, max_length=30, null=True)),
                ('cash', models.FloatField(default=10000.0)),
                ('reset_on', models.DateTimeField(auto_now_add=True)),
                ('slack_auth', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='insights.SlackAuth')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10)),
                ('quantity', models.PositiveIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('amount', models.FloatField()),
                ('buy', models.BooleanField()),
                ('talk_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insights.TalkUser')),
            ],
        ),
        migrations.AddField(
            model_name='portfolioentry',
            name='talk_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_entries', to='insights.TalkUser'),
        ),
    ]
