# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-22 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0002_auto_20161122_0117'),
    ]

    operations = [
        migrations.AddField(
            model_name='talkuser',
            name='notification_frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('off', 'off')], default='daily', max_length=20),
        ),
    ]
